#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Nov 13, 2021 02:45:23 PM CST  platform: Windows NT
#    Nov 13, 2021 03:44:24 PM CST  platform: Windows NT
#    Nov 13, 2021 03:46:10 PM CST  platform: Windows NT
#    Nov 13, 2021 06:01:09 PM CST  platform: Windows NT

import sys
import os
import func
import cv2
import numpy as np
import matplotlib.pyplot as plt

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def onBtnModifyClick_1():
    # print('GUI_support.onBtnModifyClick_1')
    # sys.stdout.flush()
    global img
    global pre_img
    global nxt_img
    global text_get
    img_list = os.listdir('./img')
    # 取得./img中影像列表
    text_get = w.TEntry1.get()
    # 取得GUI輸入(此處為影像編號)
    IMG_L = func._pick(img_list, text_get, './img')
    # 選取影像之檔名並加載影像
    img_shape = IMG_L[1].shape[:2]
    # 計算影像大小
    pre_img = func._gray(IMG_L[0])
    nxt_img = func._gray(IMG_L[1])
    # 從BGR轉至RGB
    # pos
    img = cv2.cvtColor(IMG_L[0], cv2.COLOR_BGR2RGB)
    func._Pos(img, text_get)
    # 生成影像用以供使用者標記目標點
    func._PlotPos(img, text_get)
    # 畫上選取點


def onBtnModifyClick_2():
    global img
    src = np.load('./npy/loc_' + text_get + '.npy')
    for idx in range(2):
        print('\nPoint {}'.format(idx+1))
        pt_x, pt_y = src[idx, 0], src[idx, 1]
        PX, PY = func._flow(pre_img, nxt_img, pt_x, pt_y, func.param, init_flow=None)
        img = func._plot(img, PX, PY)

    fig = plt.figure()
    plt.imshow(img)
    plt.show()

def onBtnModifyClick_3():
    fn = text_get + '_res.png'
    sP = './res'
    cv2.imwrite(os.path.join(sP, fn), cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
    # 將結果轉回BGR使用cv2儲存
    print('\nSaved')

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()





